/*
 * MUSART_Config.h
 *
 *  Created on: Feb 19, 2023
 *      Author: Ibrahim Refaey
 */

#ifndef MUSART_CONFIG_H_
#define MUSART_CONFIG_H_

#define MAX_RECEIVE_LENGTH					256
#define USART_CLK							16000000

/********************USART1 Configurations*********************/
/*
 * MUSART1_TRANSMITTER_MODE :-
 	 * MUSART_TRANMITTER_ON
 	 * MUSART_TRANMITTER_OFF
 */
#define MUSART1_TRANSMITTER_MODE					MUSART_TRANMITTER_ON
/*
 * MUSART1_RECEIVER_MODE :-
 	 * MUSART_RECEIVER_ON
 	 * MUSART_RECEIVER_OFF
 */
#define MUSART1_RECEIVER_MODE						MUSART_RECEIVER_ON
/*
 * MUSART1_OVERSAMPLING_MODE :-
 	 * MUSART_OVER_OFF
 	 * MUSART_OVER_ON
 */
#define MUSART1_OVERSAMPLING_MODE					MUSART_OVER_OFF
/*
 * MUSART1_BAUD_RATE :-
	 * Set As Required
 */
#define MUSART1_BAUD_RATE							115200UL
/*
 * MUSART1_DATA_SIZE :-
 	 * MUSART_EIGHT_BITS
 	 * MUSART_NINE_BITS
 */
#define MUSART1_DATA_SIZE							MUSART_EIGHT_BITS
/*
 * MUSART_WAKE_MODE :-
 	 * MUSART_IDEAL_LINE
 	 * MUSART_ADDRESS_MARK
 */
#define MUSART1_WAKE_MODE							MUSART_IDEAL_LINE
/*
 * MUSART1_PARITY_CONTROL :-
 	 * MUSART_PARITY_DISABLED
 	 * MUSART_PARITY_ENABLED
 */
#define MUSART1_PARITY_CONTROL						MUSART_PARITY_DISABLED
/*
 * MUSART_PARITY_SELECTION :-
 	 * MUSART_PARITY_ODD
 	 * MUSART_PARITY_EVEN
 */
#define MUSART1_PARITY_SELECTION						MUSART_PARITY_ODD
/*
 * MUSART1_PARITY_ERROR_INTERRUPT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART1_PARITY_ERROR_INTERRUPT_STATE			MUSART_INTERRUPT_DISABLED
/*
 * MUSART1_TRANSMIT_REGISTER_EMPTY_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART1_TRANSMIT_REGISTER_EMPTY_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART1_TRANSMITTION_COMPLETE_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART1_TRANSMITTION_COMPLETE_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART1_RECEIVER_REGISTER_NOT_EMPTY_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART1_RECEIVER_REGISTER_NOT_EMPTY_INTERRPUT_STATE		MUSART_INTERRUPT_ENABLED
/*
 * MUSART1_IDLE_LINE_INTERRUPT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART1_IDLE_LINE_INTERRUPT_STATE						MUSART_SEND_BREAK_DISABLED
/*
 * MUSART1_SEND_BREAK_MODE :-
 	 * MUSART_SEND_BREAK_ENABLED
 	 * MUSART_SEND_BREAK_DISABLED
 */
#define MUSART1_SEND_BREAK_MODE								MUSART_SEND_BREAK_ENABLED
/*
 * MUSART1_STOP_BITS
 	 * MUSART_1_STOP_BIT
 	 * MUSART_0_5_STOP_BIT
 	 * MUSART_2_STOP_BITS
 	 * MUSART_1_5_STOP_BITS
 */
#define MUSART1_STOP_BITS							MUSART_1_STOP_BIT

/********************USART2 Configurations*********************/

/*
 * MUSART2_TRANSMITTER_MODE :-
 	 * MUSART_TRANMITTER_ON
 	 * MUSART_TRANMITTER_OFF
 */
#define MUSART2_TRANSMITTER_MODE					MUSART_TRANMITTER_ON
/*
 * MUSART2_RECEIVER_MODE :-
 	 * MUSART_RECEIVER_ON
 	 * MUSART_RECEIVER_OFF
 */
#define MUSART2_RECEIVER_MODE						MUSART_RECEIVER_ON
/*
 * MUSART2_OVERSAMPLING_MODE :-
 	 * MUSART_OVER_OFF
 	 * MUSART_OVER_ON
 */
#define MUSART2_OVERSAMPLING_MODE					MUSART_OVER_OFF
/*
 * MUSART2_BAUD_RATE :-
	 * Set As Required
 */
#define MUSART2_BAUD_RATE							9600UL
/*
 * MUSART2_DATA_SIZE :-
 	 * MUSART_EIGHT_BITS
 	 * MUSART_NINE_BITS
 */

#define MUSART2_DATA_SIZE							MUSART_EIGHT_BITS
/*
 * MUSART_WAKE_MODE :-
 	 * MUSART_IDEAL_LINE
 	 * MUSART_ADDRESS_MARK
 */
#define MUSART2_WAKE_MODE							MUSART_IDEAL_LINE
/*
 * MUSART2_PARITY_CONTROL :-
 	 * MUSART_PARITY_DISABLED
 	 * MUSART_PARITY_ENABLED
 */
#define MUSART2_PARITY_CONTROL						MUSART_PARITY_ENABLED
/*
 * MUSART_PARITY_SELECTION :-
 	 * MUSART_PARITY_ODD
 	 * MUSART_PARITY_EVEN
 */
#define MUSART2_PARITY_SELECTION						MUSART_PARITY_ODD
/*
 * MUSART2_PARITY_ERROR_INTERRUPT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART2_PARITY_ERROR_INTERRUPT_STATE			MUSART_INTERRUPT_DISABLED
/*
 * MUSART2_TRANSMIT_REGISTER_EMPTY_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART2_TRANSMIT_REGISTER_EMPTY_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART2_TRANSMITTION_COMPLETE_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART2_TRANSMITTION_COMPLETE_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART2_RECEIVER_REGISTER_NOT_EMPTY_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART2_RECEIVER_REGISTER_NOT_EMPTY_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART2_IDLE_LINE_INTERRUPT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART2_IDLE_LINE_INTERRUPT_STATE						MUSART_INTERRUPT_DISABLED
/*
 * MUSART2_SEND_BREAK_MODE :-
 	 * MUSART_SEND_BREAK_ENABLED
 	 * MUSART_SEND_BREAK_DISABLED
 */
#define MUSART2_SEND_BREAK_MODE								MUSART_SEND_BREAK_ENABLED
/*
 * MUSART2_STOP_BITS
 	 * MUSART_1_STOP_BIT
 	 * MUSART_0_5_STOP_BIT
 	 * MUSART_2_STOP_BITS
 	 * MUSART_1_5_STOP_BITS
 */
#define MUSART2_STOP_BITS							MUSART_1_STOP_BIT


/********************USART6 Configurations*********************/

/*
 * MUSART6_TRANSMITTER_MODE :-
 	 * MUSART_TRANMITTER_ON
 	 * MUSART_TRANMITTER_OFF
 */
#define MUSART6_TRANSMITTER_MODE					MUSART_TRANMITTER_OFF
/*
 * MUSART6_RECEIVER_MODE :-
 	 * MUSART_RECEIVER_ON
 	 * MUSART_RECEIVER_OFF
 */
#define MUSART6_RECEIVER_MODE						MUSART_RECEIVER_OFF
/*
 * MUSART6_OVERSAMPLING_MODE :-
 	 * MUSART_OVER_OFF
 	 * MUSART_OVER_ON
 */
#define MUSART6_OVERSAMPLING_MODE					MUSART_OVER_OFF
/*
 * MUSART6_BAUD_RATE :-
	 * Set As Required
 */
#define MUSART6_BAUD_RATE							9600UL
/*
 * MUSART6_DATA_SIZE :-
 	 * MUSART_EIGHT_BITS
 	 * MUSART_NINE_BITS
 */
#define MUSART6_DATA_SIZE							MUSART_EIGHT_BITS
/*
 * MUSART_WAKE_MODE :-
 	 * MUSART_IDEAL_LINE
 	 * MUSART_ADDRESS_MARK
 */
#define MUSART6_WAKE_MODE							MUSART_IDEAL_LINE
/*
 * MUSART6_PARITY_CONTROL :-
 	 * MUSART_PARITY_DISABLED
 	 * MUSART_PARITY_ENABLED
 */
#define MUSART6_PARITY_CONTROL						MUSART_PARITY_ENABLED
/*
 * MUSART_PARITY_SELECTION :-
 	 * MUSART_PARITY_ODD
 	 * MUSART_PARITY_EVEN
 */
#define MUSART6_PARITY_SELECTION						MUSART_PARITY_ODD
/*
 * MUSART6_PARITY_ERROR_INTERRUPT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART6_PARITY_ERROR_INTERRUPT_STATE			MUSART_INTERRUPT_DISABLED
/*
 * MUSART6_TRANSMIT_REGISTER_EMPTY_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART6_TRANSMIT_REGISTER_EMPTY_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART6_TRANSMITTION_COMPLETE_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART6_TRANSMITTION_COMPLETE_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART6_RECEIVER_REGISTER_NOT_EMPTY_INTERRPUT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART6_RECEIVER_REGISTER_NOT_EMPTY_INTERRPUT_STATE		MUSART_INTERRUPT_DISABLED
/*
 * MUSART6_IDLE_LINE_INTERRUPT_STATE :-
 	 * MUSART_INTERRUPT_ENABLED
 	 * MUSART_INTERRUPT_DISABLED
 */
#define MUSART6_IDLE_LINE_INTERRUPT_STATE						MUSART_INTERRUPT_DISABLED
/*
 * MUSART6_SEND_BREAK_MODE :-
 	 * MUSART_SEND_BREAK_ENABLED
 	 * MUSART_SEND_BREAK_DISABLED
 */
#define MUSART6_SEND_BREAK_MODE								MUSART_SEND_BREAK_ENABLED
/*
 * MUSART6_STOP_BITS
 	 * MUSART_1_STOP_BIT
 	 * MUSART_0_5_STOP_BIT
 	 * MUSART_2_STOP_BITS
 	 * MUSART_1_5_STOP_BITS
 */
#define MUSART6_STOP_BITS							MUSART_1_STOP_BIT


#endif /* MUSART_CONFIG_H_ */
